// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import { ReduxProvider } from './reduxStore/ReduxProvider'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ReduxProvider>
//           {children}
//         </ReduxProvider>
//       </body>
//     </html>
//   )
// }
// app/layout.js
import "./globals.css";
import UserProvider from "./contextApi/contextApi/UserProvider";

export const metadata = {
  title: "Context API App",
  description: "Using Context API with fetch",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
